#!/bin/bash
if [ $# -eq 1 ] && [ $1 == "clean" ]; then
   echo "Cleanning"...
   rm -fr Makefile Makefile.in install-sh missing
   rm -fr aclocal.m4 autom4te.cache config.* configure fpga-helpers-*
   rm -fr src/Makefile src/Makefile.in
   git checkout ChangeLog
else
   echo "Running autoreconf (autotools)..."
   autoreconf -i -f
   grep -oP '\d\.\d\.\d-?d?e?v?' configure.ac > VERSION
fi
